### model
model_name_or_path: Qwen/Qwen3.5-27B
adapter_name_or_path: outputs/sft/qwen3_5_27b_npc_lora
template: qwen3_5_nothink
trust_remote_code: true

### method
finetuning_type: lora

### export
export_dir: outputs/sft/qwen3_5_27b_npc_merged
export_size: 5
export_device: cpu
export_legacy_format: false
